variables:
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "true"
  GIT_SUBMODULE_STRATEGY: recursive
  PROXY: "-Dhttp.proxyHost=cache-etu.univ-artois.fr -Dhttp.proxyPort=3128 -Dhttps.proxyHost=cache-etu.univ-artois.fr -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=localhost"
#SONARINFO: "-Dsonar.host.url=http://sonarqube.univ-artois.fr/ -Dsonar.login=$SONARTOKEN -Dsonar.projectName=TDD2021_$CI_PROJECT_NAMESPACE -Dsonar.projectKey=tdd2021_$CI_PROJECT_NAMESPACE"


stages:
- build
- test

gradle:
  image: gradle:7.2.0-jdk11
  stage: build
  script: 
  - gradle --warning-mode all $PROXY build

  tags:
    - docker2

test:
  image: gradle:7.2.0-jdk17
  stage: test
  script: 
  - gradle $PROXY test

  tags: 
    - docker2
